### ISSUE TITLE
[1.9.0] Trailmaking crashes 

### ISSUE THREAD

**Issue by cheesealmighty** [cheesealmighty/PsiNorm#16]

**Comment by cheesealmighty** [comment]
Crashlog: 

```
ERROR:root:
Bu dosyayı email ile b.bahadirakbulut@gmail.com adresine gönderiniz.

--------------------------------------------------------------------
PsiNorm - Versiyon 1.9.1
--------------------------------------------------------------------

    
Traceback (most recent call last):
  File "PsiNorm.py", line 3117, in <module>
  File "PsiNorm.py", line 3102, in progStructure
  File "PsiNorm.py", line 2561, in mainStartup
  File "PsiNorm.py", line 2416, in mainMenu
  File "PsiNorm.py", line 2994, in funcTestTemplate
TypeError: 'NoneType' object is not subscriptable

```

Trailmaking dict: null should be [null, null]
